name: Sitio web con docker

on: [push]

permissions:
  contents: read

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -name: Mensaje de Saludo 
        run:
        echo "Hola Mundo"